### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by debris** [paritytech/parity-bitcoin#1]
- [x] primitives
  - [x] hash
  - [x] bytes
- [x] serialization
  - [x] serialize trait
  - [x] deserialize trait
  - [x] compact integers
  - [x] serialization of primitives
- [x] crypto
  - [x] ripemd160
  - [x] sha1
  - [x] sha256
  - [x] dhash160
  - [x] dhash256
- [x] chain
  - [x] transaction
    - [x] serialization
    - [x] tx hash
  - [x] block_header
    - [x] serialization
  - [x] block
    - [x] serialization
    - [x] hash
  - [x] merkle_root
- [x] [base58](https://github.com/debris/base58)
- [ ] keys
  - [x] random generation
  - [x] compressed keys
  - [ ] addresses
    - [x] P2PKH
    - [ ] P2SH
    - [x] serialization to/from string
  - [x] signatures
    - [x] sign
    - [x] sign_compact
    - [x] recover_compact
    - [x] verify
- [x] script
  - [x] interpreter
    - [x] eval
    - [x] verify
  - [x] pretty display
  - [x] signing transaction input
- [x] message
  - [x] common
  - [x] message types
  - [x] serialization
- [x] p2p
  - [x] handshake
  - [x] dispatching messages
- [ ] CI
  - [x] travis for private repos
  - [ ] coveralls
  - [ ] documentation
