### ISSUE TITLE
Sync improvements for slow networks

### ISSUE THREAD

**Issue by svyatonik** [paritytech/parity-bitcoin#298]
Just not to forget lessons I've learned using this wifi:
- [x] requests to sync peers should be ordered. let scheduled_queue = [b0, b1, b2, b3]. let fast_peers = [p0, p1] where p0 responds faster than p1. So p0 shuld be asked for [b0, b1] and p1 for [b2, b3]
- [ ] there should be a chance for 'forgotten' peers to be 'remembered' again. They should be asked for blocks from time to time (these should be duplicated requests!!!) - sync will be much faster && the price is just receiving at most extra 1MB. Another option is to drop connection to such -peers
- [ ] we should ask for blocks in more aggressive way - i.e. duplicating should occur more often. Because it's more important task to get current work for verification queue, than to make long verification queue 
- [ ] get rid (in favor of dynamic calculation, basing on blocks response time [which increases with height]) of hardcoded sync constants DEFAULT_PEER_BLOCK_FAILURE_INTERVAL_MS + DEFAULT_PEER_INVENTORY_FAILURE_INTERVAL_MS (or at least decrease these constants). MAX_PEER_FAILURES should be increased 
- [ ] get rid of hardcoded sync constants MIN_BLOCKS_IN_REQUEST + MAX_BLOCKS_IN_REQUEST: number of blocks in request should be calculated basing on len(scheduled_queue) + len(verification_queue) + sync speed + verification speed + number of available peers
- [ ] NEAR_EMPTY_VERIFICATION_QUEUE_THRESHOLD_BLOCKS + NEAR_EMPTY_VERIFICATION_QUEUE_THRESHOLD_S must be replaced with some criteria that will guarantee that filling speed of verification queue will be greater than verification speed. This duplicating must also take into account 'forgotten' peers
