### ISSUE TITLE
Backports from parity-zcash

### ISSUE THREAD

**Issue by svyatonik** [paritytech/parity-bitcoin#543]
- [x] [Minimize chain structures hashing (part#1)](https://github.com/paritytech/parity-zcash/pull/59)
 - [x] [Penalize peer when receiving unknown headers message](https://github.com/paritytech/parity-zcash/pull/61)
- [x] [Minimize chain structures hashing (part#2)](https://github.com/paritytech/parity-zcash/pull/63)
- [x] [Disable TransactionDoubleSpend for coinbase transactions](https://github.com/paritytech/parity-zcash/pull/71) (probably even merge `pruning` branch before merging that?)
- [x] [Cache transaction outputs in ChainAcceptor](https://github.com/paritytech/parity-zcash/pull/72)
- [x] [Name all spawned threads](https://github.com/paritytech/parity-zcash/pull/73)
- [x] [Hash header(s) without holding sync lock](https://github.com/paritytech/parity-zcash/pull/74)
- [x] [Display actual import error when import has failed](https://github.com/paritytech/parity-zcash/pull/76)
- [x] [Handle reorganizations during blocks import](https://github.com/paritytech/parity-zcash/pull/78)
- [x] [Ignore zero-filled gaps in blk files](https://github.com/paritytech/parity-zcash/pull/83)
- [x] [Improve error reporting in import handler](https://github.com/paritytech/parity-zcash/pull/86)

Non-mandatory candidates:
- [ ] [Verify headers in separate thread](https://github.com/paritytech/parity-zcash/pull/67) + [Fixed panic when header is verifying for (Verifying | Stored) block](https://github.com/paritytech/parity-zcash/pull/99)
- [ ] [Actually verify headers](https://github.com/paritytech/parity-zcash/pull/69)
- [ ] [Do not verify headers twice during synchronization](https://github.com/paritytech/parity-zcash/pull/70)
